@REM This file was automatically generated by alyxlib.
@REM Run this file before uploading your addon to the workshop, then follow window instructions after uploading.
@echo off

rmdir "C:\Program Files (x86)\Steam\steamapps\common\Half-Life Alyx\content\hlvr_addons\resin_watch\scripts\vscripts\alyxlib"
del "C:\Program Files (x86)\Steam\steamapps\common\Half-Life Alyx\content\hlvr_addons\resin_watch\scripts\vlua_globals.lua"
rmdir "C:\Program Files (x86)\Steam\steamapps\common\Half-Life Alyx\content\hlvr_addons\resin_watch\scripts\vscripts\game"

echo Symlinks have been removed, continue after uploading to workshop.
PAUSE
echo.

mklink /d "C:\Program Files (x86)\Steam\steamapps\common\Half-Life Alyx\content\hlvr_addons\resin_watch\scripts\vscripts\game" "C:\Program Files (x86)\Steam\steamapps\common\Half-Life Alyx\content\hlvr_addons\alyxlib\scripts\vscripts\game"
echo.
mklink /d "C:\Program Files (x86)\Steam\steamapps\common\Half-Life Alyx\content\hlvr_addons\resin_watch\scripts\vscripts\game" "C:\Program Files (x86)\Steam\steamapps\common\Half-Life Alyx\content\hlvr_addons\alyxlib\scripts\vscripts\game"
echo.
mklink /d "C:\Program Files (x86)\Steam\steamapps\common\Half-Life Alyx\content\hlvr_addons\resin_watch\scripts\vscripts\game" "C:\Program Files (x86)\Steam\steamapps\common\Half-Life Alyx\content\hlvr_addons\alyxlib\scripts\vscripts\game"
echo.

echo Symlinks reinstated! This window can now be closed.
PAUSE
